using UnityEditor;
using UnityEngine;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;

[CustomEditor(typeof(UIBase), true)]
public class UIBaseInspector : Editor
{
    List<string> _autoFields = new List<string>();

    void OnEnable()
    {
        CacheAutoGeneratedFields();
    }

    public override void OnInspectorGUI()
    {
        serializedObject.Update();

        // 1️⃣ 画自动生成字段（灰色）
        DrawAutoGeneratedFields();

        EditorGUILayout.Space();

        // 2️⃣ 画其余正常字段
        DrawPropertiesExcluding(
            serializedObject,
            _autoFields.Append("m_Script").ToArray()
        );

        serializedObject.ApplyModifiedProperties();

        GUILayout.Space(10);
        GUILayout.Label("UI 自动绑定", EditorStyles.boldLabel);

        if (GUILayout.Button("🔧 生成 UI 绑定代码"))
        {
            UIAutoBindGenerator.Generate(target as UIBase);
        }
    }

    void CacheAutoGeneratedFields()
    {
        _autoFields.Clear();

        var type = target.GetType();
        var fields = type.GetFields(
            BindingFlags.Instance |
            BindingFlags.NonPublic |
            BindingFlags.Public);

        foreach (var f in fields)
        {
            if (!f.Name.StartsWith("_"))
                continue;

            if (!typeof(Component).IsAssignableFrom(f.FieldType))
                continue;

            _autoFields.Add(f.Name);
        }
    }

    void DrawAutoGeneratedFields()
    {
        if (_autoFields.Count == 0)
            return;

        EditorGUILayout.LabelField("Auto Generated Bindings", EditorStyles.boldLabel);

        EditorGUI.BeginDisabledGroup(true);

        foreach (var name in _autoFields)
        {
            var prop = serializedObject.FindProperty(name);
            if (prop != null)
            {
                EditorGUILayout.PropertyField(prop);
            }
        }

        EditorGUI.EndDisabledGroup();
    }
}
